### PR TITLE
Proposing an additional theme and icon redesigning

### PR DESCRIPTION
**Pull request by DN-debug**
Hi Vini, 

This might be completely irrelevant, but I am actually suggesting a universal dark theme called Knight [ derived from Kimi-dark gtk theme ], darker than Darcula . 
Also proposing the redesigning of the logo [ I've kept in mind to match it with existing one but rather made it flat ] . 

Please review, if the proposition doesn't suit you well, you may decline it. 

Below is the snap of how the interface will look along with tray-icon.

image

logo:
image

logo_update:
image

### CODE REVIEW

**Comment by vinifmor** [comment]
Hi @DN-debug, that's great. I'm going to review the theme as soon as possible. In relation to the default icon: it would be ideal to submit the proposal in a different PullRequest

**Comment by DN-debug** [comment]
> Hi @DN-debug, that's great. I'm going to review the theme as soon as possible. In relation to the default icon: it would be ideal to submit the proposal in a different PullRequest

Sounds good to me, I will remove the logos from this current PR, and will create a separate one and attach them there. Thanks!

**Comment by DN-debug** [comment]
Sorry Vini, had to make couple of back and forth commits, as I accidentally remove the resource/img from my version of the Fork. Corrected that and its all good now to review. Thanks!

**Comment by vinifmor** [comment]
@DN-debug , this PR is removing the current logos

**Comment by vinifmor** [comment]
A doubt: have you checked if the initialization panel's style is as expected ?

knight_init

**Comment by DN-debug** [comment]
> @DN-debug , this PR is removing the current logos

Yes, you are right, i thought that removing the new logos wouldn't affect it but it did, nevertheless I've just added the current logos back into the branch.

**Comment by DN-debug** [comment]
> A doubt: have you checked if the initialization panel's style is as expected ?
> 
> knight_init

Yes, that is how it looks like. If you have any suggestions to that, i can modify it.

**Comment by vinifmor** [comment]
@DN-debug , not at all. I was just confirming if it was ok.

**Comment by vinifmor** [comment]
@DN-debug , your changes are already available on the **staging** branch of AUR (bauh-staging)

**Pull request merged**
