### PR TITLE
MANIFEST.in: Include LICENSE, docs and tests

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
The sdist needs these things.  distros use them to create their packages, and they need to run the tests on them,

**Comment by vinifmor** [comment]
Alright. I will include the tests folder.

**Comment by jayvdb** [comment]
So then you will re-open this PR, and I will drop `pictures` and `aur` directories?

**Comment by vinicius-moreira-dafiti** [comment]
Hi @jayvdb , I had already included in **0.7.1**. Thank you for you help anyway.

**Comment by vinifmor** [comment]
Hi @jayvdb , I had already included in **0.7.1**. Thank you for help anyway.

**Pull request closed without merging**
