### PR TITLE
Proposal for updating the default logo 

### PR DESCRIPTION
**Pull request by DN-debug**
Hi Vini, 

This new PR is coming from #223. Hope this time its done correctly. 

Thanks!

### CODE REVIEW

**Comment by vinifmor** [comment]
@DN-debug  well done ! The proposed logo is great. 

Since bauh has not implemented a behavior for pre-selecting a logo based on the system's theme colors (dark/light), it would be better if the chest's wood was just a little lighter (to look nice in any desktop theme). See the how it looks a little faded on my dark tray:

bauh_new_logo

Besides that, everything is fine.

**Comment by DN-debug** [comment]
> @DN-debug well done ! The proposed logo is great.
> 
> Since bauh has not implemented a behavior for pre-selecting a logo based on the system's theme colors (dark/light), it would be better if the chest's wood was just a little lighter (to look nice in any desktop theme). See the how it looks a little faded on my dark tray:
> 
> bauh_new_logo
> 
> Besides that, everything is fine.

Hi Vini, just made a quick refurbishment on these logos, removed the heavy shadows and changed the color a bit, now its a little lighter, let me know if this is ok, otherwise I will polish them a bit more.

**Comment by vinifmor** [comment]
It seems fine. I'm going to test it with some different desktop themes and let you know.

**Comment by vinifmor** [comment]
I've attached to images of the tray for a dark and light theme. Tell me your thoughts

bauh-tray-light

bauh-tray-dark

**Comment by DN-debug** [comment]
While not being biased to my low designing skills, I'd say the contrast looks good to me when seen along with the other respective tray icons, except Mega, which is a very sharp in contrast as opposed to the other icons.

**Comment by vinifmor** [comment]
Great. I'm going to merge it here. The new logo really makes a difference. Thank you for helping the project.

**Comment by vinifmor** [comment]
Already available on the **staging** branch (AUR)

**Pull request merged**
