### PR TITLE
Add Catalan translation

### PR DESCRIPTION
**Pull request by fitojb**

### CODE REVIEW

**Comment by vinifmor** [comment]
Hi @fitojb , thank you for your effort in translating the app for Catalan. Would you mind translating also the keys for the specific packaging types before I merge this PR  ? The files are located in the folders below:

https://github.com/vinifmor/bauh/tree/master/bauh/gems/appimage/resources/locale
https://github.com/vinifmor/bauh/tree/master/bauh/gems/arch/resources/locale
https://github.com/vinifmor/bauh/tree/master/bauh/gems/snap/resources/locale
https://github.com/vinifmor/bauh/tree/master/bauh/gems/flatpak/resources/locale

Thanks again, my friend.

**Comment by fitojb** [comment]
Done, sorry for the delay.

**Comment by vinifmor** [comment]
No worries. I will be testing here if nothing breaks. Actually I will change the code to not break the app if a translation key is not found. Just a doubt: what's returned for a system with catalan as the default language when you execute the following command on a terminal `python -c "import locale;  print(locale.getdefaultlocale());"` ?

**Comment by vinifmor** [comment]
Already figured out here. Merging your PR.

**Comment by vinifmor** [comment]
If you use an Arch-based system: your merged PR is already available in the package **bauh-staging** (version 0.7.3-RC2).

**Pull request merged**
