### PR TITLE
add german translation

### PR DESCRIPTION
**Pull request by JonasLoos**
Not tested in app

### CODE REVIEW

**Comment by vinifmor** [comment]
Hello @JonasLoos , thank you for bringing the German translations for bauh. I will be testing it to see if nothing breaks and merge your PR. Thanks again for your effort.

**Comment by vinifmor** [comment]
@JonasLoos, by default the current bauh version gets the default string for some english words, so I didn't put them in the **en** files. To help people with translations, I put all the missing 'en' keys in their respective files. Could you add them to your PR ? This commit contains the missing keys:

https://github.com/vinifmor/bauh/commit/3bd493e22560679191becf4d26d0d761b140c7a8

**Comment by JonasLoos** [comment]
I added the translations, hope I forgot nothing. I recommend you test it again before merging.

**Comment by vinifmor** [comment]
It's ok. I added a new behavior to the staging branch if it does not find a key, it will get the english version. Merging your PR...

**Pull request merged**
